### ISSUE TITLE
Orange Icons

### ISSUE THREAD

**Issue by dadofsambonzuki** [bubelov/btcmap-android#21]
Make the vendor icons orange.

**Comment by bubelov** [comment]
Someone is using a dark mode =)

Orange color is problematic for dark mode and new Android systems don't even allow bright colors for app launcher icons if the preference is set to dark.

![device-2022-09-03-151414](https://user-images.githubusercontent.com/1189245/188262265-25185baf-7c65-4a1b-8c78-2d92dd489f2e.png)

**Comment by dadofsambonzuki** [comment]
😂
